export const productdata = [
{
    productname:"",
    productimage:"",
    productprice:"",
    productamount:""
},
{
    productname:"",
    productimage:"",
    productprice:"",
    productamount:""
},
{
    productname:"",
    productimage:"",
    productprice:"",
    productamount:""
},
{
    productname:"",
    productimage:"",
    productprice:"",
    productamount:""
},
{
    productname:"",
    productimage:"",
    productprice:"",
    productamount:""
},{
    productname:"",
    productimage:"",
    productprice:"",
    productamount:""
},{
    productname:"",
    productimage:"",
    productprice:"",
    productamount:""
},{
    productname:"",
    productimage:"",
    productprice:"",
    productamount:""
},{
    productname:"",
    productimage:"",
    productprice:"",
    productamount:""
},

]